management:
  security:
    enabled: false
  health:
    probes:
      enabled: true

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  artemis:
    mode: native
    host: ${GATEWAY_JMS_HOST:localhost}
    user: ${GATEWAY_JMS_USERNAME}
    password: ${GATEWAY_JMS_PASSWORD}
    port: ${GATEWAY_JMS_PORT:5445}
  security:
    oauth2:
      client:
        registration:
          offender-search-client:
            client-name: offender-search-client
            client-id: ${offender-search-client-id:offender-search-client}
            client-secret: ${offender-search-client-secret:clientsecret}
            client-authentication-method: basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
        provider:
          nomis-oauth-service:
            token-uri: ${nomis-oauth.base-url:http://oauth:8095}/auth/oauth/token

court-case-service:
  case-put-url-template: /court/%s/case/%s

offender-search:
  post-match-url: /match

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 5000
    write-timeout-ms: 5000

# court name to codes is a simple look up until CGI provide the change to their feed
case-mapper-reference:
  defaultProbationStatus: "No record"
  courtNameToCodes:
    Sheffield Magistrates Court: "SHF"


